import { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { ChangeEvent, useState } from 'react';
import Loading from '../../components/loading.component';
import { Sidebar } from '../../components/sidebar.component';
import { SectionHeading } from '../../components/typography.component';
import { MainLayout } from '../../layouts/main.layout';
import { trpc } from '../../utils/trpc';

const HouseholdDetails = () => {
  const router = useRouter();
  const id = router.query.id as string;

  const [selectedUser, setSelectedUser] = useState('');

  const { data, isLoading } = trpc.useQuery([
    'household.get-household',
    { id },
  ]);

  function onSelectUser(e: ChangeEvent<HTMLSelectElement>) {
    setSelectedUser(e.currentTarget.value);
  }

  if (isLoading) {
    return <Loading />;
  }

  return (
    <>
      <Head>
        <title>{data?.name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SectionHeading>{data?.name}</SectionHeading>
      <p>
        {data?.addressLine1} {data?.addressLine2}, {data?.city}, {data?.state}{' '}
        {data?.zipCode}
      </p>

      {data?.images &&
        data.images.map((image) => (
          <img
            className="max-w-xs h-48"
            src={image.url}
            alt={image.alt || 'Image of home'}
          />
        ))}

      <SectionHeading>Users</SectionHeading>
      {data?.householdsOnUsers &&
        data.householdsOnUsers.map((hou) => (
          <p>{hou.user.displayName || hou.user.name}</p>
        ))}

      <SectionHeading>Tasks</SectionHeading>
      {data?.tasks && data.tasks.map((task) => <p>{task.name}</p>)}

      <SectionHeading>Groceries</SectionHeading>
      {data?.groceries &&
        data.groceries.map((grocery) => <p>{grocery.name}</p>)}

      <SectionHeading>Pets</SectionHeading>
      {data?.pets && data.pets.map((pet) => <p>{pet.name}</p>)}
    </>
  );
};

const Household: NextPage = () => {
  return (
    <MainLayout>
      <HouseholdDetails />
    </MainLayout>
  );
};

export default Household;
