import { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { Sidebar } from '../../components/sidebar.component';
import { trpc } from '../../utils/trpc';

const HouseholdDetails = () => {
  const router = useRouter();
  const id = router.query.id as string;

  const { data, isLoading } = trpc.useQuery([
    'household.get-household',
    { id },
  ]);

  if (isLoading) {
    return (
      <>
        <p>Loading...</p>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>{data?.name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>{data?.name}</h2>
    </>
  );
};

const Household: NextPage = () => {
  return (
    <div className="flex">
      <Sidebar />
      <HouseholdDetails />
    </div>
  );
};

export default Household;
