import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '../utils/trpc';
import { Sidebar } from '../components/sidebar.component';
import { TiledList } from '../components/tiledList.component';
import { AddHouseholdForm } from '../components/addHouseholdForm.component';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex">
        <Sidebar />
        <div className="flex-1">
          <AddHouseholdForm />
          <TiledList query={'household.my-households'} header="Households" />
          <TiledList query={'household.invited'} header="Pending Invites" />
        </div>
      </div>
    </>
  );
};

export default Home;
